layout_spectrum: 0.2657594756282276
typography_spectrum: 0.10723427717601604
color:
  brandStrength: 0.47135298755416405
  lightness: 0.6686617724679521
  saturation: 0.3551362448173695
  rhythmicContrast: 0.540670687136434
  brandColors:
    - '#105B63'
    - '#FFFAD5'
    - '#FFD34E'
    - '#DB9E36'
    - '#BD4932'
github: true
author:
  name: Clarence Dillon
  email: cdillon2@gmu.edu
  url: studycomplexity.io
logo: null
name: Alternative World Futures
url: 'https://www.studycomplexity.io'
navigation:
  - name: About
    id: 70e64726-63b8-4192-a889-5880a41b08e4
    type: content
  - name: 'Summary '
    id: 00dc742c-bf77-4d4d-95ea-36572c1c8287
    type: content
favicon: >-
  https://the-grid-user-content.s3-us-west-2.amazonaws.com/99efbe34-78fb-4c39-abb6-3501168eca54.png
title: Studies on Global Social Complexity
content:
  - id: !<tag:yaml.org,2002:js/undefined> ''
    type: image
    html: >-
      <img
      src="https://the-grid-user-content.s3-us-west-2.amazonaws.com/c08fd4e4-e06c-4570-844f-6bc3d87271ba.png">
    src: >-
      https://the-grid-user-content.s3-us-west-2.amazonaws.com/c08fd4e4-e06c-4570-844f-6bc3d87271ba.png
    metadata:
      author: []
      related: []
      publisher:
        url: 'https://the-grid-user-content.s3-us-west-2.amazonaws.com'
        name: The-grid-user-content
        favicon: null
        domain: the-grid-user-content.s3-us-west-2.amazonaws.com
      keywords: []
      description: ''
      app_links: []
      '@context': 'http://schema.org'
      '@type': MediaObject
      datePublished: null
    title: !<tag:yaml.org,2002:js/undefined> ''
    caption: !<tag:yaml.org,2002:js/undefined> ''
    text: !<tag:yaml.org,2002:js/undefined> ''
  - id: !<tag:yaml.org,2002:js/undefined> ''
    type: image
    html: >-
      <img
      src="https://the-grid-user-content.s3-us-west-2.amazonaws.com/db8909b4-fb47-4e48-8360-3afd57a1cd74.png">
    src: >-
      https://the-grid-user-content.s3-us-west-2.amazonaws.com/db8909b4-fb47-4e48-8360-3afd57a1cd74.png
    metadata:
      author: []
      related: []
      publisher:
        url: 'https://the-grid-user-content.s3-us-west-2.amazonaws.com'
        name: The-grid-user-content
        favicon: null
        domain: the-grid-user-content.s3-us-west-2.amazonaws.com
      keywords: []
      description: ''
      app_links: []
      '@context': 'http://schema.org'
      '@type': MediaObject
      datePublished: null
    title: !<tag:yaml.org,2002:js/undefined> ''
    caption: !<tag:yaml.org,2002:js/undefined> ''
    text: !<tag:yaml.org,2002:js/undefined> ''
  - id: !<tag:yaml.org,2002:js/undefined> ''
    type: image
    html: >-
      <img
      src="https://the-grid-user-content.s3-us-west-2.amazonaws.com/d0bc559a-aec6-45c2-80cc-9054938892b0.png">
    src: >-
      https://the-grid-user-content.s3-us-west-2.amazonaws.com/d0bc559a-aec6-45c2-80cc-9054938892b0.png
    metadata:
      author: []
      related: []
      publisher:
        url: 'https://the-grid-user-content.s3-us-west-2.amazonaws.com'
        name: The-grid-user-content
        favicon: null
        domain: the-grid-user-content.s3-us-west-2.amazonaws.com
      keywords: []
      description: ''
      app_links: []
      '@context': 'http://schema.org'
      '@type': MediaObject
      datePublished: null
    title: !<tag:yaml.org,2002:js/undefined> ''
    caption: !<tag:yaml.org,2002:js/undefined> ''
    text: !<tag:yaml.org,2002:js/undefined> ''
  - id: !<tag:yaml.org,2002:js/undefined> ''
    type: image
    html: >-
      <img
      src="https://the-grid-user-content.s3-us-west-2.amazonaws.com/9e347df8-374b-4d63-8457-1348cfeb6601.png">
    src: >-
      https://the-grid-user-content.s3-us-west-2.amazonaws.com/9e347df8-374b-4d63-8457-1348cfeb6601.png
    metadata:
      author: []
      related: []
      publisher:
        url: 'https://the-grid-user-content.s3-us-west-2.amazonaws.com'
        name: The-grid-user-content
        favicon: null
        domain: the-grid-user-content.s3-us-west-2.amazonaws.com
      keywords: []
      description: ''
      app_links: []
      '@context': 'http://schema.org'
      '@type': MediaObject
      datePublished: null
    title: !<tag:yaml.org,2002:js/undefined> ''
    caption: !<tag:yaml.org,2002:js/undefined> ''
    text: !<tag:yaml.org,2002:js/undefined> ''
  - id: !<tag:yaml.org,2002:js/undefined> ''
    type: image
    html: >-
      <img
      src="https://the-grid-user-content.s3-us-west-2.amazonaws.com/d56ee0df-e1b8-425b-8d94-dadb364c055a.png">
    src: >-
      https://the-grid-user-content.s3-us-west-2.amazonaws.com/d56ee0df-e1b8-425b-8d94-dadb364c055a.png
    metadata:
      author: []
      related: []
      publisher:
        url: 'https://the-grid-user-content.s3-us-west-2.amazonaws.com'
        name: The-grid-user-content
        favicon: null
        domain: the-grid-user-content.s3-us-west-2.amazonaws.com
      keywords: []
      description: ''
      inLanguage: !<tag:yaml.org,2002:js/undefined> ''
      app_links: []
      '@context': 'http://schema.org'
      '@type': MediaObject
      datePublished: null
    title: !<tag:yaml.org,2002:js/undefined> ''
    caption: !<tag:yaml.org,2002:js/undefined> ''
    text: !<tag:yaml.org,2002:js/undefined> ''
description: The ins and outs of my studies on social complexity at the global level
purpose:
  - type: external
    url: 'https://twitter.com/CWDillon'
    label: Tweet at me
analytics:
  twitter: '#studycomplexity'
