layout_spectrum: 0.2649698458209929
typography_spectrum: 0.43070292636115876
color:
  brandStrength: 0.6084850363834475
  lightness: 0.6347243371361516
  saturation: 0.35190622110546815
  rhythmicContrast: 0.7438061073317312
  brandColors:
    - '#B4AF91'
    - '#787746'
    - '#40411E'
    - '#32331D'
    - '#C03000'
github: true
author:
  name: Clarence Dillon
  email: cdillon2@gmu.edu
  url: studycomplexity.io
logo: null
name: Alternative World Futures
url: 'https://www.studycomplexity.io'
navigation:
  - name: About
    id: 70e64726-63b8-4192-a889-5880a41b08e4
    type: content
  - name: 'Summary '
    id: 00dc742c-bf77-4d4d-95ea-36572c1c8287
    type: content
favicon: >-
  https://the-grid-user-content.s3-us-west-2.amazonaws.com/99efbe34-78fb-4c39-abb6-3501168eca54.png
title: Studies on Global Social Complexity
content:
  - id: !<tag:yaml.org,2002:js/undefined> ''
    type: image
    html: >-
      <img
      src="https://the-grid-user-content.s3-us-west-2.amazonaws.com/33bcdf8d-d82c-4e2f-8066-cb176cb0dc88.jpg">
    src: >-
      https://the-grid-user-content.s3-us-west-2.amazonaws.com/33bcdf8d-d82c-4e2f-8066-cb176cb0dc88.jpg
    metadata:
      author: []
      related: []
      publisher:
        url: 'https://the-grid-user-content.s3-us-west-2.amazonaws.com'
        name: The-grid-user-content
        favicon: null
        domain: the-grid-user-content.s3-us-west-2.amazonaws.com
      keywords: []
      description: ''
      app_links: []
      '@context': 'http://schema.org'
      '@type': MediaObject
      datePublished: null
    title: !<tag:yaml.org,2002:js/undefined> ''
    caption: !<tag:yaml.org,2002:js/undefined> ''
    text: !<tag:yaml.org,2002:js/undefined> ''
description: The ins and outs of my studies on social complexity at the global level
purpose:
  - type: external
    url: 'https://twitter.com/CWDillon'
    label: Tweet at me
analytics:
  twitter: '#studycomplexity'
