typography_spectrum: 0.8801791967839777
color:
  brandStrength: 0.533738294625286
  lightness: 0.6053015427299692
  saturation: 0.26448127921052866
  rhythmicContrast: 0.5707297605354485
  brandColors:
    - '#FFF8E3'
    - '#CCCC9F'
    - '#33332D'
    - '#9FB4CC'
    - '#DB4105'
github: true
layout_spectrum: 0.26806184743743133
author:
  name: Clarence Dillon
  email: cdillon2@gmu.edu
  url: studycomplexity.io
logo: null
name: Alternative World Futures
url: 'https://www.studycomplexity.io'
navigation:
  - name: About
    id: 70e64726-63b8-4192-a889-5880a41b08e4
    type: content
  - name: 'Summary '
    id: 00dc742c-bf77-4d4d-95ea-36572c1c8287
    type: content
favicon: >-
  https://the-grid-user-content.s3-us-west-2.amazonaws.com/99efbe34-78fb-4c39-abb6-3501168eca54.png
title: Studies on Global Social Complexity
content:
  - id: !<tag:yaml.org,2002:js/undefined> ''
    type: image
    html: >-
      <img
      src="https://the-grid-user-content.s3-us-west-2.amazonaws.com/c08fd4e4-e06c-4570-844f-6bc3d87271ba.png">
    src: >-
      https://the-grid-user-content.s3-us-west-2.amazonaws.com/c08fd4e4-e06c-4570-844f-6bc3d87271ba.png
    metadata:
      author: []
      related: []
      publisher:
        url: 'https://the-grid-user-content.s3-us-west-2.amazonaws.com'
        name: The-grid-user-content
        favicon: null
        domain: the-grid-user-content.s3-us-west-2.amazonaws.com
      keywords: []
      description: ''
      app_links: []
      '@context': 'http://schema.org'
      '@type': MediaObject
      datePublished: null
    title: !<tag:yaml.org,2002:js/undefined> ''
    caption: !<tag:yaml.org,2002:js/undefined> ''
    text: !<tag:yaml.org,2002:js/undefined> ''
  - id: !<tag:yaml.org,2002:js/undefined> ''
    type: image
    html: >-
      <img
      src="https://the-grid-user-content.s3-us-west-2.amazonaws.com/db8909b4-fb47-4e48-8360-3afd57a1cd74.png">
    src: >-
      https://the-grid-user-content.s3-us-west-2.amazonaws.com/db8909b4-fb47-4e48-8360-3afd57a1cd74.png
    metadata:
      author: []
      related: []
      publisher:
        url: 'https://the-grid-user-content.s3-us-west-2.amazonaws.com'
        name: The-grid-user-content
        favicon: null
        domain: the-grid-user-content.s3-us-west-2.amazonaws.com
      keywords: []
      description: ''
      inLanguage: !<tag:yaml.org,2002:js/undefined> ''
      app_links: []
      '@context': 'http://schema.org'
      '@type': MediaObject
      datePublished: null
    title: !<tag:yaml.org,2002:js/undefined> ''
    caption: !<tag:yaml.org,2002:js/undefined> ''
    text: !<tag:yaml.org,2002:js/undefined> ''
description: The ins and outs of my studies on social complexity at the global level
purpose:
  - type: external
    url: 'https://twitter.com/CWDillon'
    label: Tweet at me
analytics:
  twitter: '#studycomplexity'
