layout_spectrum: 0.2657594756282276
typography_spectrum: 0.10723427717601604
color:
  brandStrength: 0.47135298755416405
  lightness: 0.6686617724679521
  saturation: 0.3551362448173695
  rhythmicContrast: 0.540670687136434
  brandColors:
    - '#105B63'
    - '#FFFAD5'
    - '#FFD34E'
    - '#DB9E36'
    - '#BD4932'
github: true
author:
  name: Clarence Dillon
  email: cdillon2@gmu.edu
  url: studycomplexity.io
logo: null
name: Alternative World Futures
url: 'https://www.studycomplexity.io'
navigation:
  - name: About
    id: 70e64726-63b8-4192-a889-5880a41b08e4
    type: content
  - name: 'Summary '
    id: 00dc742c-bf77-4d4d-95ea-36572c1c8287
    type: content
favicon: >-
  https://the-grid-user-content.s3-us-west-2.amazonaws.com/99efbe34-78fb-4c39-abb6-3501168eca54.png
title: Studies on Global Social Complexity
content: []
description: The ins and outs of my studies on social complexity at the global level
purpose:
  - type: external
    url: 'https://twitter.com/CWDillon'
    label: Tweet at me
analytics:
  twitter: '#studycomplexity'
